# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Global Speleothem Analysis Reveals State-Dependent Rainbelt Response to Orbital Forcing
author: Alexander James
logo: logo.png
copyright: "2024"
only_build_toc_files: true
execute:
  execute_notebooks: force
  timeout: 3600

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/alexkjames/Speleothems_and_Insolation
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
  announcement: ""

launch_buttons:
  notebook_interface: "jupyterlab"
  binderhub_url: ""